---
title: "Untitled"
author: "Dan Kluger"
date: "10/21/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
RandomSubsetFixedSize <- function(FormattedDatInp,N_samp,clusterSample=F){
  
  FormattedDatSubset <- list()

  if(clusterSample){
    uniqueClusters <- unique(FormattedDatInp$ClusterIDs)
    NClusters <- length(uniqueClusters)
    ExpectedNClustSubsamp <- NClusters* N_samp/nrow(FormattedDatInp$GoodDat)
    rem <- ExpectedNClustSubsamp-floor(ExpectedNClustSubsamp)
    NClustSubsamp <- floor(ExpectedNClustSubsamp)+ sample(c(0,1),size = 1,prob = c(1-rem,rem))
    ClusterIDsSubsamp <- sample(uniqueClusters,size = NClustSubsamp,replace = F)
    idxSubsample <- which(FormattedDatInp$ClusterIDs %in% ClusterIDsSubsamp)
  } else{
    MSuper <- nrow(FormattedDatInp$GoodDat)
    idxSubsample <- sample(1:MSuper,size = N_samp,replace = F) #Resampling without replacement as in main text
  }
  
  FormattedDatSubset$GoodDat <- FormattedDatInp$GoodDat[idxSubsample,]
  FormattedDatSubset$ProxyDat <- FormattedDatInp$ProxyDat[idxSubsample,]
  
  
  
    if(!is.null(FormattedDatInp$PiLabelUnsc)){FormattedDatSubset$PiLabelUnsc <- FormattedDatInp$PiLabelUnsc[idxSubsample]} 
    else{ FormattedDatSubset$PiLabelUnsc <- NULL}
   if(!is.null(FormattedDatInp$ClusterIDs)){FormattedDatSubset$ClusterIDs <- FormattedDatInp$ClusterIDs[idxSubsample]} 
  else{ FormattedDatSubset$ClusterIDs <- NULL}

  return(FormattedDatSubset)
}
```


```{r}
LabelRandomSubset <- function(GoodDatInp,ProxyDatInp,piLabelInpUsnc=NULL,nLabelTarget){
  if(is.null(piLabelInpUsnc)){
      piLabelRescaled <- rep(nLabelTarget/nrow(GoodDatInp),nrow(GoodDatInp))
  } else {
      piLabelRescaled <- nLabelTarget*piLabelInpUsnc/sum(piLabelInpUsnc)
  }
  Idx2Label <- I(runif(n = nrow(GoodDatInp)) < piLabelRescaled)
  GoodDatWMissing <- GoodDatInp
  GoodDatWMissing[!Idx2Label,] <- NA
  return(list(GoodDatWMissing=GoodDatWMissing,piLabelRescaled=piLabelRescaled))
}
```

```{r}
LabelRandomSubsetofClusters <- function(GoodDatInp,ProxyDatInp,piLabelInpUsnc=NULL,clustersInp,nLabelTarget){
  
  if(is.null(piLabelInpUsnc)){
      uniqueClusterIDs <- unique(clustersInp)
      piClusterRescaled <- rep(nLabelTarget/nrow(GoodDatInp),length(uniqueClusterIDs))
      piLabelRescaled <- rep(nLabelTarget/nrow(GoodDatInp),nrow(GoodDatInp))
  } else {
     clusterInp2 <- clustersInp
      piClusterDf <- data.frame(piLabelInpUsnc,clusterInp2) %>% group_by(clusterInp2) %>% summarise(piCluster=mean(piLabelInpUsnc),ClusterSize=n())
      piClusterRescaled <- nLabelTarget*piClusterDf$piCluster/sum(piClusterDf$piCluster*piClusterDf$ClusterSize)
      piLabelRescaled <- nLabelTarget*piLabelInpUsnc/sum(piLabelInpUsnc)
      uniqueClusterIDs <- piClusterDf[['clusterInp2']]
  }
  
  
  Clusters2Label <- I(runif(n = length(uniqueClusterIDs)) < piClusterRescaled)
  Idx2Label <- rep(NA,nrow(GoodDatInp))
  for(i in 1:length(uniqueClusterIDs)){
    Idx2Label[clustersInp==uniqueClusterIDs[i]] <- Clusters2Label[i]
  }
  GoodDatWMissing <- GoodDatInp
  GoodDatWMissing[!Idx2Label,] <- NA
  return(list(GoodDatWMissing=GoodDatWMissing,piLabelRescaled=piLabelRescaled))
}
```



```{r}
library(dplyr)
SoftwareImplementationPath <- paste0(dirname(getwd()),"/PTD_Boot_Implementation/")
source(paste0(SoftwareImplementationPath,"PTDBootModularized.R"))
source(paste0(SoftwareImplementationPath,"BootstrapAndCalcEsts.R"))
source(paste0(SoftwareImplementationPath,"EstBetaGammaCalib_andVCOV.glm.R"))
source(paste0(SoftwareImplementationPath,"FormatAndFitReg.R"))
```

```{r}
runSimsRealData <- function(FormattedDatInp2,N_sampInp,nLabelTargInp,nSims=100,regTypeInp="linear",outcomeVarName="Y",BootstrapSchemesInp=c("FullBootPercentile","QuickConvolution","CLTBased"),tuningSchemesInp=c("Optimal","Diagonal","None"),alphaInp=0.1,clusteredLabelling=F,useClusterIDs=F,tauForQuantileReg=NULL){

  
  SimResultList <- list()

  runTimeVec <- rep(NA,nSims)
  for(i in 1:nSims){
    FormattedDatSubsamp <- RandomSubsetFixedSize(FormattedDatInp = FormattedDatInp2,N_samp = N_sampInp,clusterSample = clusteredLabelling)
    
    if(clusteredLabelling){
      CurrLabelling <- LabelRandomSubsetofClusters(GoodDatInp = FormattedDatSubsamp$GoodDat,
                                       ProxyDatInp = FormattedDatSubsamp$ProxyDat,
                                       piLabelInpUsnc = FormattedDatSubsamp$PiLabelUnsc,
                                       clustersInp = FormattedDatSubsamp$ClusterIDs,
                                       nLabelTarget = nLabelTargInp)
    }else{
      CurrLabelling <- LabelRandomSubset(GoodDatInp = FormattedDatSubsamp$GoodDat,
                                       ProxyDatInp = FormattedDatSubsamp$ProxyDat,
                                       piLabelInpUsnc = FormattedDatSubsamp$PiLabelUnsc,
                                       nLabelTarget = nLabelTargInp)
    }
    
  if(useClusterIDs){
    ClustersUse <- FormattedDatSubsamp$ClusterIDs
  } else{
    ClustersUse <- NULL
  }

    InitTimeBeforeRunCurr <- proc.time()[3]
    suppressWarnings(SimResultList[[i]] <- PTDBootModularized(ProxyDat = FormattedDatSubsamp$ProxyDat,GoodDat = CurrLabelling$GoodDatWMissing,PiLabel = CurrLabelling$piLabelRescaled,clusterID=ClustersUse ,BootstrapScheme=BootstrapSchemesInp,nBootInference = 2000,nBootTune = 0,TuningScheme = tuningSchemesInp,RegType = regTypeInp,OutcomeVarName = outcomeVarName,alpha = alphaInp,tauQuantReg = tauForQuantileReg)) 
    runTimeVec[i] <- proc.time()[3]-InitTimeBeforeRunCurr
    
  }
  
  return(list(SimResultList=SimResultList,N_sampInp=N_sampInp,nLabelTargInp=nLabelTargInp,RegTypeUsed=regTypeInp,alphaUsed=alphaInp,tauForQuantileRegUsed=tauForQuantileReg,runTimeVec=runTimeVec)) 
}
```



```{r}
RunSuiteGetRuntime <- function(nLabelTargVecInp,N_sampVecInp,nSimsPerSpecInp,FormattedDatInp2,CLTBasedAvailable=TRUE,regTypeInp2,outcomeVarNameInp2,clusteredLabellingInp2 = F,useClusterIDsInp2 = F,tauForQuantileRegInp2=NULL){
  
  RunTimeResultsMat <- matrix(NA,nrow = length(nLabelTargVecInp)*length(N_sampVecInp),ncol = 8)
  colnames(RunTimeResultsMat) <- c("n","N","CLT","CLT_SE","SpeedupBoot","SpeedupBootSE","FullBoot","FullBootSE")
  
  idxCount <- 0
  for(i in 1:length(nLabelTargVecInp)){
    for(j in 1:length(N_sampVecInp)){
      idxCount <- idxCount+1
      RunTimeResultsMat[idxCount,'n'] <- nLabelTargVecInp[i]
      RunTimeResultsMat[idxCount,'N'] <- N_sampVecInp[j] #Originally said i but now fixed
      
      
      print(c(i,j))
      
      if(CLTBasedAvailable==T){
        CLTRuntimes <- runSimsRealData(FormattedDatInp = FormattedDatInp2,nSims = nSimsPerSpecInp,N_sampInp = N_sampVecInp[j],nLabelTargInp = nLabelTargVecInp[i],regTypeInp = regTypeInp2,outcomeVarName = outcomeVarNameInp2,BootstrapSchemesInp = c("CLTBased"),tuningSchemesInp = "Diagonal",clusteredLabelling = clusteredLabellingInp2 ,useClusterIDs = useClusterIDsInp2,tauForQuantileReg = tauForQuantileRegInp2)$runTimeVec
        
        RunTimeResultsMat[idxCount,'CLT'] <- mean(CLTRuntimes)
        RunTimeResultsMat[idxCount,'CLT_SE'] <- sd(CLTRuntimes)/sqrt(nSimsPerSpecInp)
              print(CLTRuntimes)

      }
      
      
      QuickConvolutionRuntimes <- runSimsRealData(FormattedDatInp = FormattedDatInp2,nSims = nSimsPerSpecInp,N_sampInp = N_sampVecInp[j],nLabelTargInp = nLabelTargVecInp[i],regTypeInp = regTypeInp2,outcomeVarName = outcomeVarNameInp2,BootstrapSchemesInp = c("QuickConvolution"),tuningSchemesInp = "Diagonal",clusteredLabelling = clusteredLabellingInp2 ,useClusterIDs = useClusterIDsInp2,tauForQuantileReg = tauForQuantileRegInp2)$runTimeVec

      RunTimeResultsMat[idxCount,'SpeedupBoot'] <- mean(QuickConvolutionRuntimes)
      RunTimeResultsMat[idxCount,'SpeedupBootSE'] <- sd(QuickConvolutionRuntimes)/sqrt(nSimsPerSpecInp)
      print(QuickConvolutionRuntimes)
      FullBootRuntimes <- runSimsRealData(FormattedDatInp = FormattedDatInp2,nSims = nSimsPerSpecInp,N_sampInp = N_sampVecInp[j],nLabelTargInp = nLabelTargVecInp[i],regTypeInp = regTypeInp2,outcomeVarName = outcomeVarNameInp2,BootstrapSchemesInp = c("FullBootPercentile"),tuningSchemesInp = "Diagonal",clusteredLabelling = clusteredLabellingInp2 ,useClusterIDs = useClusterIDsInp2,tauForQuantileReg = tauForQuantileRegInp2)$runTimeVec
      
      RunTimeResultsMat[idxCount,'FullBoot'] <- mean(FullBootRuntimes)
      RunTimeResultsMat[idxCount,'FullBootSE'] <- sd(FullBootRuntimes)/sqrt(nSimsPerSpecInp)
      print(FullBootRuntimes)

      
      
    }
  }
  return(RunTimeResultsMat)
  
}
```


```{r}
nLabelTargVec <- c(100,200,400,800)
nSimsPerSpec <- 5
N_sampVec <- c(1000)*2^(seq(0,5))

#Quick trial run
#nLabelTargVec <- 100
#nSimsPerSpec <- 1
#N_sampVec <- 1000

```



Check Runtimes
```{r}
set.seed(9)

#Housing price linear regression (Experiment 2)
load(paste0(dirname(getwd()),"/Datasets/","HousingPriceFormatted.RData"))


HousingPriceRuntimesLR <- RunSuiteGetRuntime(nLabelTargVecInp = nLabelTargVec,N_sampVecInp = N_sampVec,nSimsPerSpecInp = nSimsPerSpec,FormattedDatInp2 = HousingPriceFormatted,CLTBasedAvailable = T,regTypeInp2 = "linear",outcomeVarNameInp2 = "HousingPrice")



#Housing price quantile regression (Experiment 3)

HousingPriceSimsQuantileRegMedianRuntimes <- RunSuiteGetRuntime(nLabelTargVecInp = nLabelTargVec,N_sampVecInp = N_sampVec,nSimsPerSpecInp = nSimsPerSpec,FormattedDatInp2 = HousingPriceFormatted,CLTBasedAvailable = F,regTypeInp2 = "Quantile Regression",outcomeVarNameInp2 = "HousingPrice",tauForQuantileRegInp2 = 0.5)


save(HousingPriceRuntimesLR,HousingPriceSimsQuantileRegMedianRuntimes,file = paste0(getwd(),"/Results/HousingPriceRuntimes.RData"))

  
```


Had to run rest at another time

```{r}
set.seed(10)
#Binarized Treecover Regression (Experiment 6)

load(paste0(dirname(getwd()),"/Datasets/","TreecoverBinarizedFormatted.RData"))

#100 with logistic regression sometimes returs an error
TreecoverBinarizedSimsRuntime <- RunSuiteGetRuntime(nLabelTargVecInp = nLabelTargVec,N_sampVecInp = N_sampVec,nSimsPerSpecInp = nSimsPerSpec,FormattedDatInp2 = TreecoverBinarizedFormatted,CLTBasedAvailable = FALSE,regTypeInp2 = "logistic",outcomeVarNameInp2 = "Forest") # Could get CLT ones but not including in plot
  

save(TreecoverBinarizedSimsRuntime,file = paste0(getwd(),"/Results/TreecoverLogisticRuntimes.RData"))

  
  
```

```{r}
set.seed(11)
#Ordinal Regression (Experiment 8)
#nLabelBigger <- c(400,800) #c(100,200,400,800)
N_sampVecSaller <- c(1000)*2^(seq(0,4)) #using smaller N because otherwise it will take a while

load(paste0(dirname(getwd()),"/Datasets/CensusStratEducationFormatted.RData"))


#200 or lower with logistic regression sometimes returs an error
CensusOrdinalSimsRuntime_n400 <- RunSuiteGetRuntime(nLabelTargVecInp = 400,N_sampVecInp = N_sampVecSaller,nSimsPerSpecInp = nSimsPerSpec,FormattedDatInp2 = EducationDatFormatted,CLTBasedAvailable = FALSE,regTypeInp2 = "ordinal",outcomeVarNameInp2 = "Education") 

#200 or lower with logistic regression sometimes returs an error
CensusOrdinalSimsRuntime_n800 <- RunSuiteGetRuntime(nLabelTargVecInp = 800,N_sampVecInp = N_sampVecSaller[2:length(N_sampVecSaller)],nSimsPerSpecInp = nSimsPerSpec,FormattedDatInp2 = EducationDatFormatted,CLTBasedAvailable = FALSE,regTypeInp2 = "ordinal",outcomeVarNameInp2 = "Education") 
  

save(CensusOrdinalSimsRuntime_n400,CensusOrdinalSimsRuntime_n800,file = paste0(getwd(),"/Results/CensusOrdinalRegRuntimes.RData"))
```


Making figure
```{r}
load(paste0(getwd(),"/Results/HousingPriceRuntimes.RData"))
load(paste0(getwd(),"/Results/TreecoverLogisticRuntimes.RData"))
load(paste0(getwd(),"/Results/CensusOrdinalRegRuntimes.RData"))
LinearRegExamples <- data.frame(HousingPriceRuntimesLR) %>% mutate(Model=rep("(2) Linear Regression",nrow(HousingPriceRuntimesLR)))

QuantileRegExamples <- data.frame(HousingPriceSimsQuantileRegMedianRuntimes) %>% mutate(Model=rep("(3) Quantile Regression",nrow(HousingPriceSimsQuantileRegMedianRuntimes)))


LogisticRegressionExamples <- data.frame(TreecoverBinarizedSimsRuntime) %>% mutate(Model=rep("(6) Logistic Regression",nrow(TreecoverBinarizedSimsRuntime)))

#Giving Ordinal regresion result matrix same dimension (with NAs for missing)
OrdinalRegressionExampleMat <- TreecoverBinarizedSimsRuntime
OrdinalRegressionExampleMat[,colnames(OrdinalRegressionExampleMat)[3:ncol(OrdinalRegressionExampleMat)]] <- NA
for(i in 1:nrow(OrdinalRegressionExampleMat)){
  if((OrdinalRegressionExampleMat[i,'n']==400)){
    idxCurr <- which((CensusOrdinalSimsRuntime_n400[,'n']==OrdinalRegressionExampleMat[i,'n']) & (CensusOrdinalSimsRuntime_n400[,'N']==OrdinalRegressionExampleMat[i,'N']))
    if(length(idxCurr)>0){
      OrdinalRegressionExampleMat[i,] <- CensusOrdinalSimsRuntime_n400[idxCurr,]
    }
  }
  
  if((OrdinalRegressionExampleMat[i,'n']==800)){
    idxCurr <- which((CensusOrdinalSimsRuntime_n800[,'n']==OrdinalRegressionExampleMat[i,'n']) & (CensusOrdinalSimsRuntime_n800[,'N']==OrdinalRegressionExampleMat[i,'N']))
    if(length(idxCurr)>0){
    OrdinalRegressionExampleMat[i,] <- CensusOrdinalSimsRuntime_n800[idxCurr,]
    }
  }
}

OrdinalRegressionExamples <- data.frame(OrdinalRegressionExampleMat) %>% mutate(Model=rep("(8) Ordinal Regression",nrow(OrdinalRegressionExampleMat)))


RuntimeDf <- rbind(LinearRegExamples,QuantileRegExamples,LogisticRegressionExamples,OrdinalRegressionExamples)
```

```{r}
library(dplyr)
library(tidyr)

dfRuntime_long <- RuntimeDf %>%
  pivot_longer(
    cols = c(CLT, CLT_SE, SpeedupBoot, SpeedupBootSE, FullBoot, FullBootSE),
    names_to = "col"
  ) %>%
  mutate(
    Method = case_when(
      grepl("^CLT", col)         ~ "CLT",
      grepl("^Speedup", col)     ~ "Speedup",
      grepl("^FullBoot", col)    ~ "FullBoot"
    ),
    type = ifelse(grepl("SE", col), "SERuntime", "MeanRuntime")
  ) %>%
  dplyr::select(-col) %>%
  pivot_wider(names_from = type, values_from = value)

```

```{r}
library(ggplot2)


color_scale_ManualCIs <- scale_color_manual(values = c("#d896ff","#65fe08"))
pointShapeManual <- scale_shape_manual(values = c(17,18))
ptSizeManual <- scale_size_manual(values = c(0.5,3))

pltTheme <- theme(axis.text.y = element_text(size=8),panel.grid.major.x = element_blank(),panel.grid.major.y = element_line(size=0.2),panel.grid.minor = element_blank(),legend.text = element_text(size=10),strip.text.y = element_text(size=7.5))
#Make Figure 3

dfRuntime_long$nTitle <- paste0("E[n]=",dfRuntime_long$n)

dfRuntime_long$Method[dfRuntime_long$Method=="FullBoot"] <- "Full PTD Bootstrap (Algorithm 2)"
dfRuntime_long$Method[dfRuntime_long$Method=="Speedup"] <- "PTD Bootstrap Speedup (Algorithm 3)"

#Removing large N and CLT because they make plot harder to read (larger N follows same pattern)
p1 <- ggplot(dfRuntime_long %>% filter(Method!="CLT", N!=32000), aes(x = N, y = MeanRuntime, color = Method,shape=Method)) +
  geom_point( size = 1.5) +
  geom_errorbar(
    aes(ymin = MeanRuntime - 2*SERuntime, ymax = MeanRuntime + 2*SERuntime),
    width = 0.1,alpha=1
  ) +
  facet_grid( Model ~ nTitle ,switch="y",scales = "free_y") +
  labs(x = "N (Total Number of Samples)", y = "Mean Runtime (Seconds)") +
  theme_bw() +
  theme(legend.position = "bottom")+pointShapeManual+color_scale_ManualCIs+ptSizeManual+pltTheme+scale_x_log10() +
scale_y_log10()

ggsave(
paste0(getwd(),"/Figures/Runtimes.pdf"),
  plot = p1,height = 6.5
)

```





